#!/usr/bin/env python3
"""Generates lib/mock-data/intel-cards.json, beware-entries.json, community-posts.json."""
import json, os

OUT = "/home/user/TravelApp/lib/mock-data"
os.makedirs(OUT, exist_ok=True)

# ── helpers ──────────────────────────────────────────────────────────────────

def card(slug, dest, audience, contributor, verified, hero,
         tldr, hoods, scams, transport, gems,
         checklist, dos, donts, budget, emergency,
         premium=False, premium_preview="", affiliates={}):
    return {
        "slug": slug, "destination": dest, "country": "India",
        "audience": audience, "contributorSlug": contributor,
        "lastUpdated": "2026-04-10", "verifiedByCount": verified,
        "heroImageUrl": hero,
        "tldr": tldr,
        "neighborhoods": hoods,
        "scams": scams,
        "transport": transport,
        "hiddenGems": gems,
        "preBookChecklist": checklist,
        "dosAndDonts": {"do": dos, "dont": donts},
        "estimatedDailyBudget": {**budget, "currency": "INR"},
        "emergencyNumbers": emergency,
        "isPremium": premium,
        "premiumPreview": premium_preview,
        "affiliateLinks": affiliates,
    }

def hood(name, rating, vibe, stay, notes):
    return {"name": name, "safetyRating": rating, "vibe": vibe,
            "stayHere": stay, "notes": notes}

def scm(title, severity, where, what, avoid):
    return {"title": title, "severity": severity, "where": where,
            "what": what, "avoid": avoid}

def trn(mode, tip, cost):
    return {"mode": mode, "tip": tip, "approxCost": cost}

def gem(name, type_, angle, why, cost):
    return {"name": name, "type": type_, "angle": angle,
            "why": why, "approxCost": cost}

def emg(label, number):
    return {"label": label, "number": number}

# ── intel cards ──────────────────────────────────────────────────────────────
intel_cards = [

# 1 ── GOA ────────────────────────────────────────────────────────────────────
card(
    "goa-india", "Goa", "both", "ananya-mumbai", 12,
    "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    tldr=[
        "Goa taxi union blocks Uber/Ola in most areas — use GoaMiles app (govt-backed, fixed fares).",
        "Drug possession setups on beaches are not myths; NDPS Act means 1+ year jail, no bail.",
        "Never give your passport as scooter-rental collateral — photograph every scratch before you ride.",
        "North Goa for energy and nightlife; South Goa (Palolem, Agonda) for quiet and yoga.",
        "Book accommodation 3+ months ahead for Dec 20 – Jan 10; prices triple without notice.",
    ],
    hoods=[
        hood("Assagao", 5, "Boutique cafés, female-founder stays, quiet lanes", True,
             "The Project Café is here. Safer than Anjuna, walkable to Vagator. Best first base."),
        hood("Anjuna / Vagator", 3, "Party beach, flea market, lively nights", False,
             "Highest drug-offer and overcharge density. Great energy; go with a group after dark."),
        hood("Palolem, South Goa", 4, "Backpacker beach, yoga, sunset shacks", True,
             "Cleanest solo-female-friendly beach. Silent Noise Club on Saturdays is unmissable."),
    ],
    scams=[
        scm("Fake hotel/villa booking", "critical", "Online — Instagram, WhatsApp",
            "AI-generated photos, fake booking sites. You pay ₹20K–₹2L and arrive to nothing. Raised in Rajya Sabha 2025.",
            "Book only via Booking.com, MakeMyTrip, or direct hotel website. Call hotel to confirm before paying."),
        scm("Drug possession setup", "critical", "Anjuna, Vagator, Baga beaches",
            "Stranger offers drugs; 'plainclothes cop' appears immediately demanding bribe. Minimum 1-year jail under NDPS Act.",
            "Zero tolerance. Walk away from all unsolicited beach offers. Never accept cigarettes from strangers."),
        scm("Scooter rental damage claim", "high", "All rental shops",
            "Pre-existing scratches 'discovered' on return; deposit or passport held hostage for 'repair' costs.",
            "Photograph every centimetre of the bike before riding. Never surrender your passport. Use Royal Brothers app."),
        scm("GoaMiles impersonation", "high", "Dabolim and Mopa airports",
            "Unofficial drivers hold GoaMiles-style cards and quote fixed rates that are 2–3× the real app price.",
            "Only book through the actual GoaMiles app. Ignore anyone approaching you in the arrivals hall."),
    ],
    transport=[
        trn("GoaMiles app", "Govt-backed fixed-fare taxi. Book before landing. Only reliable pre-paid option.", "₹800–1,200 airport → North Goa"),
        trn("Scooter (Royal Brothers / Onn Bikes app)", "App-based rental with GPS insurance. Saves ₹1,500+/day vs taxis.", "₹350–500/day"),
        trn("Kadamba state bus", "Safe, AC inter-city routes. Panaji ↔ Margao ↔ Mapusa.", "₹15–60"),
    ],
    gems=[
        gem("The Project Café, Aldona", "Boutique stay + café", "Female-founded",
            "All-women team, 130-year Portuguese mansion. Pool, art books, design-forward interiors. The insider solo-women pick.", "Stay ₹6,000–15,000/night; café open to non-guests"),
        gem("Sappadu, Assagao", "Restaurant", "Female-owned",
            "Women-run South Indian veg restaurant. Homely thalis, no tourist markup. Featured Tweak India 2025.", "Meal ₹350–700"),
        gem("Mapusa Friday Market", "Market", "Authentic Goan",
            "Real Goan market without the Anjuna hawker scrum. Arrive 8am for fish section, leave before 11am heat.", "Free entry; budget ₹500–2,000"),
    ],
    checklist=[
        "Book accommodation via Booking.com and call hotel to confirm reservation",
        "Download GoaMiles app before your flight lands",
        "Save Goa Police helpline in phone: 0832-2423400",
        "Buy travel insurance (World Nomads covers scooter accidents in India)",
        "Check NGT/pollution odd-even days if visiting in peak season",
    ],
    dos=[
        "Use only GoaMiles or pre-agreed fixed taxi fares — no street negotiations",
        "Photograph scooter 360° before and after every rental",
        "Carry a door-stop alarm for hostel/guesthouse rooms",
        "Stick to South Goa beaches if it's your first solo India trip",
    ],
    donts=[
        "Hand over your passport as collateral for any rental or deposit",
        "Accept anything from strangers on beaches — not even fruit",
        "Trust anyone claiming to be an off-duty police officer demanding documentation",
        "Book Goa villas or party packages through Instagram DMs",
    ],
    budget={"backpacker": 2500, "midRange": 5500, "comfortable": 12000},
    emergency=[emg("Goa Police Control", "100"), emg("Women's Helpline", "1091"),
               emg("Tourist Police Panaji", "0832-2423400"), emg("Ambulance", "108")],
    premium=True,
    premium_preview="Premium covers: the 3 hostels that actively vet solo female guests, full GoaMiles booking walkthrough with screenshots, a complete Palolem vs Agonda vs Patnem comparison, and the November shoulder-season hack that cuts mid-range accommodation costs by 40%.",
    affiliates={"booking": "https://www.booking.com/searchresults.html?ss=Goa&aid=PLACEHOLDER",
                "worldNomads": "https://www.worldnomads.com/travel-insurance?affiliate=PLACEHOLDER"},
),

# 2 ── JAIPUR ─────────────────────────────────────────────────────────────────
card(
    "jaipur-india", "Jaipur", "both", "neha-jaipur", 14,
    "https://images.unsplash.com/photo-1477013144938-7c68caa9f76a?w=800&q=80",
    tldr=[
        "Every auto near Hawa Mahal will try to take you to a commission shop — use Uber/Ola only.",
        "Old City is best at dawn (7–9am) before heat and touts both hit peak intensity.",
        "No real 'government gem emporium' exists at tourist spots — every one of them is commission-based.",
        "Nahargarh Fort after 4pm is dramatically less crowded and the light is better.",
        "Heritage havelis in Bani Park give you proximity to sights without the Old City chaos.",
    ],
    hoods=[
        hood("Bani Park", 4, "Residential, heritage hotels, quiet streets", True,
             "15 min from all major sights, none of the Old City noise. Most solo female travelers prefer staying here."),
        hood("Old City (Pink City)", 3, "Heritage architecture, dense markets", False,
             "Beautiful but exhausting solo. Go with a plan, use app taxis, leave before dusk."),
        hood("C-Scheme / MI Road", 4, "Modern area, cafés, safe evenings", True,
             "For evenings out — Tapri, Curious Life Coffee, Maa restaurant. Feels like any Indian metro."),
    ],
    scams=[
        scm("Gem/stone shop commission", "high", "Near all major monuments",
            "Auto/guide takes you to 'government emporium'; pressure sale of overpriced stones. Driver earns 30–50% cut.",
            "Book rides on Uber/Ola only. Any shop described as 'government approved' near a tourist site is not."),
        scm("Carpet / textile commission loop", "high", "Near Amber Fort, City Palace",
            "Multi-person tag-team sales with fake 'export price' discounts and manufactured urgency.",
            "Shop independently in Johri Bazaar or Bapu Bazaar. Leave any shop you were taken to by a driver."),
        scm("Fake entry tickets", "medium", "Amber Fort queue",
            "Touts sell 'skip-the-line' tickets outside the gate. Tickets are counterfeit; you pay twice.",
            "Buy tickets only at official ASI counters or on the ASI India website. No legitimate queue-skip exists."),
        scm("Elephant ride 'tip' demand", "medium", "Amber Fort approach road",
            "Ride priced at ₹500; aggressive tip and animal feed demands post-ride with crowd pressure.",
            "Skip elephant rides entirely (ethical + overpriced). Amber Fort jeep taxi ₹200 is faster and cheaper."),
    ],
    transport=[
        trn("Uber / Ola", "Both work reliably in Jaipur. Always preferred over street autos.", "₹80–250 within city"),
        trn("Auto-rickshaw (metered)", "Insist on meter. Hawa Mahal → City Palace benchmark: ₹40–60.", "₹30–150"),
        trn("Day-hire car + driver", "Best for Amber + Nahargarh + Jal Mahal loop. Ask hotel to arrange.", "₹1,500–2,500/day"),
    ],
    gems=[
        gem("Nahargarh Fort at sunset", "Fort / viewpoint", "Crowd-free after 4pm",
            "Best views of Jaipur's pink skyline. Rooftop café open till 9pm. Army presence makes it safe.", "₹200 entry; café ₹200–500"),
        gem("Galta Ji Monkey Temple", "Temple complex", "Off tourist trail",
            "Ancient temple in a gorge — monkeys, pilgrims, zero commission touts. Best 7–9am.", "₹50 entry"),
        gem("Rajasthali Government Emporium, MI Road", "Shopping", "Genuine fixed price",
            "Actual state craft store. Fixed prices, no commission, quality Blue Pottery and block prints.", "Blue Pottery ₹500–3,000"),
    ],
    checklist=[
        "Book heritage hotel in Bani Park or Civil Lines, not the Old City",
        "Download Uber/Ola before arrival — don't negotiate with autos from monuments",
        "Buy Amber Fort tickets on ASI India website to skip the queue",
        "Check Jaipur Literature Festival dates if visiting in January",
        "Carry ₹500–1,000 in small bills for bazaar shopping",
    ],
    dos=[
        "Browse Johri Bazaar and Bapu Bazaar independently — no guide needed",
        "Visit Amber Fort at 8am opening to beat both heat and crowds",
        "Use Rajasthali on MI Road for authentic fixed-price Rajasthani crafts",
        "Ask your hotel staff (not auto drivers) for restaurant recommendations",
    ],
    donts=[
        "Accept auto rides to 'government-approved' gem or carpet shops",
        "Engage with any 'export wholesale' fabric pitch near tourist sites",
        "Share your hotel name or onward plans with persistent strangers",
        "Ride elephants at Amber Fort — choose jeep or walking instead",
    ],
    budget={"backpacker": 1800, "midRange": 4000, "comfortable": 9000},
    emergency=[emg("Jaipur Police", "100"), emg("Women's Helpline", "1091"),
               emg("Tourist Police Jaipur", "0141-5110595"), emg("Ambulance", "108")],
    premium=True,
    premium_preview="Premium covers: exact Hawa Mahal early-access hack (saves 90 min queuing), two heritage hotels with women-only floors, 8-day Rajasthan circuit itinerary (Jaipur → Jodhpur → Udaipur), and female artisan workshop visits where the money goes directly to the maker.",
    affiliates={"booking": "https://www.booking.com/searchresults.html?ss=Jaipur&aid=PLACEHOLDER"},
),

# 3 ── VARANASI ───────────────────────────────────────────────────────────────
card(
    "varanasi-india", "Varanasi", "both", "ananya-mumbai", 9,
    "https://images.unsplash.com/photo-1561361513-2d8ab5bad3f4?w=800&q=80",
    tldr=[
        "Allow 3 full days minimum — Varanasi cannot be rushed and rushing makes you a better scam target.",
        "Morning boat ride on the Ganges at sunrise is the single non-negotiable experience; book night before.",
        "Never accept 'free' blessings, sindoor, or marigolds at ghats — a donation demand follows instantly.",
        "Bhang lassi is legal here and widely served — know exactly what you're ordering before you drink.",
        "Assi Ghat area is calmer and safer for solo women than the main Dashashwamedh Ghat strip.",
    ],
    hoods=[
        hood("Assi Ghat", 4, "Quieter south end, guesthouses, yoga, cafés", True,
             "Best solo-female base. Morning yoga on the ghats, safe café culture. 20 min walk from main ghats."),
        hood("Godaulia / Dashashwamedh", 3, "Dense, intense, highest foot traffic", False,
             "Stay only if you want the full immersion. Overwhelming for first-timers. Touts are constant."),
        hood("Cantonment / Sigra", 4, "Modern, hotels, away from ghat chaos", True,
             "Budget mid-range hotels with working AC. Good if you want to retreat from the intensity."),
    ],
    scams=[
        scm("Ghat tout to silk shop", "high", "All major ghats",
            "Friendly 'student' or 'priest' offers to show you a lesser-known temple, ends at family silk shop.",
            "Decline all unsolicited guiding. Hire a licensed guide through your guesthouse only."),
        scm("Boat ride overcharge", "high", "All ghat boat launch points",
            "₹200 sunrise ride quoted; ₹2,000 demanded on return claiming 'per person, not per boat'.",
            "Fix total price and occupancy in writing (phone note, photo) before boarding. Confirm: this is total price."),
        scm("Fake Ganga Aarti 'donation'", "medium", "Dashashwamedh Ghat",
            "Man with collection box claims proceeds go to the Aarti organisation. Not affiliated.",
            "Ganga Aarti is free to watch. No official donation collection exists. Ignore all collection boxes."),
        scm("Bhang-spiked food or drink", "high", "Lassi shops, street stalls",
            "Bhang (cannabis) added to food without disclosure. Disorientation leads to theft or worse.",
            "Only order from clearly labelled bhang shops. Never accept food/drinks from strangers near ghats."),
    ],
    transport=[
        trn("Cycle rickshaw", "Best for narrow gali (lane) navigation. Agree price before riding.", "₹30–100 within ghat area"),
        trn("Auto-rickshaw", "For Cantonment ↔ ghats. Insist on meter or fixed price.", "₹50–150"),
        trn("Pre-paid taxi (station/airport)", "Book at official pre-paid counter only — ignore touts outside.", "₹300–500 from Varanasi Junction"),
    ],
    gems=[
        gem("Manikarnika Ghat at dawn", "Sacred ghat", "Off the tourist script",
            "The burning ghat is visited by many but understood by few. Go at 6am with a licensed local guide who explains context respectfully.", "Guide ₹500–800"),
        gem("Blue Lassi Shop, Godaulia", "Café", "Legendary solo stop",
            "75-year-old family-run lassi stall. The original. Cash only, arrive before 11am before the line forms.", "₹80–150"),
        gem("Ramnagar Fort", "Fort / museum", "Away from ghat crowds",
            "Across the river, no touts, old royal collection. Takes half a day. Best combined with sunset river crossing.", "₹25 entry"),
    ],
    checklist=[
        "Book sunrise boat ride through your guesthouse the evening before",
        "Carry a scarf to cover shoulders and head at all temple and ghat sites",
        "Download offline Varanasi map (Maps.me) — alleys have no signal",
        "Confirm train onward to next destination — Varanasi Junction gets very crowded",
        "Keep ₹100–200 in exact change for boat rides, rickshaws, and temple donations",
    ],
    dos=[
        "Hire only licensed guides through your guesthouse, not ghat touts",
        "Agree total boat ride price and passenger count before boarding",
        "Stay in Assi Ghat area for calmer mornings and safer evenings",
        "Attend Ganga Aarti at Dashashwamedh Ghat — arrive 30 min early for a standing spot",
    ],
    donts=[
        "Accept free marigolds, sindoor, or blessings from anyone at the ghats",
        "Drink or eat anything offered by a stranger near any ghat",
        "Follow anyone offering to show you a 'lesser-known temple' or 'secret ceremony'",
        "Photograph burning ghats without explicit permission from the family present",
    ],
    budget={"backpacker": 1500, "midRange": 3500, "comfortable": 8000},
    emergency=[emg("Varanasi Police", "100"), emg("Women's Helpline", "1091"),
               emg("Tourist Police Varanasi", "0542-2502020"), emg("Ambulance", "108")],
    premium=True,
    premium_preview="Premium covers: the 4 guesthouses with women-only floors on Assi Ghat, exact guide to navigating Manikarnika ethically, a Varanasi → Sarnath day-trip itinerary with female-led guide contact, and the Benares Hindu University campus walk (secretly one of the safest and most beautiful morning walks in the city).",
    affiliates={"booking": "https://www.booking.com/searchresults.html?ss=Varanasi&aid=PLACEHOLDER",
                "worldNomads": "https://www.worldnomads.com/travel-insurance?affiliate=PLACEHOLDER"},
),

# 4 ── MANALI ─────────────────────────────────────────────────────────────────
card(
    "manali-india", "Manali", "indian", "ananya-mumbai", 8,
    "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    tldr=[
        "Old Manali is for backpackers and café culture; New Manali has ATMs, pharmacies, and reliable transport.",
        "Rohtang Pass requires an NGT online permit — book minimum 2 days in advance, slots fill fast.",
        "July–August is peak monsoon; landslides close the Manali–Leh highway with zero warning.",
        "Altitude sickness starts around 2,050m — acclimatise for a full day before trekking anywhere.",
        "Solo after 10pm in New Manali: stay in. Old Manali lanes are fine until sunset, not after.",
    ],
    hoods=[
        hood("Old Manali", 4, "Backpacker cafés, Israeli vibe, chill lanes", True,
             "Best solo-female atmosphere. Dragon Café, Café 1947, Dylan's Toasted & Roasted. Quiet by 10pm."),
        hood("New Manali (Mall Road)", 3, "Busy, ATMs, transport, shops", False,
             "Practical for logistics; avoid budget hotels here — they face the noisy bus stand."),
        hood("Vashisht village", 4, "Hot springs, guesthouses, temple, calm", True,
             "15 min from Mall Road. Female-friendly guesthouses, sulphur hot springs, Vashisht Temple."),
    ],
    scams=[
        scm("Rohtang Pass fake permit service", "high", "Near bus stands and travel agents",
            "Touts sell 'guaranteed permits' for ₹1,500–2,000. NGT permits are free and online only.",
            "Book only at https://rohtangpermits.nic.in — free, government website. No middleman needed."),
        scm("Solang Valley overcharge", "medium", "Solang Valley activity stalls",
            "Snow activity prices quoted per-person but charged per-item post-activity with add-ons.",
            "Agree full itemised price in writing before any activity. Walk away if price changes."),
        scm("Fake trek guide", "medium", "Old Manali cafés and guesthouses",
            "Self-described guides with no certification take inexperienced trekkers on dangerous routes.",
            "Hire only ITBP-certified guides through registered trek agencies. Ask for licence number."),
    ],
    transport=[
        trn("HRTC Volvo bus (Delhi → Manali)", "Overnight AC sleeper. Most reliable option; book on HRTC website.", "₹700–1,400 Delhi → Manali"),
        trn("Shared taxi / cab", "For Solang Valley, Rohtang, Naggar. Pre-book via guesthouse.", "₹300–800/day shared"),
        trn("Local auto-rickshaw", "Within New Manali and between Vashisht and Mall Road.", "₹30–80"),
    ],
    gems=[
        gem("Naggar Castle", "Heritage fort / café", "Crowd-free heritage",
            "15th-century stone castle with Roerich Art Gallery and valley views. Almost no tourists on weekdays.", "₹100 entry"),
        gem("Café 1947, Old Manali", "Café", "Solo-women favourite",
            "The original Old Manali café. Israeli breakfast, good filter coffee, safe for solo mornings.", "Meal ₹250–500"),
        gem("Hamta Pass day trek base", "Trek", "Gateway to high-altitude",
            "Hamta Pass (4,270m) trek starts near Jobra. Day-hike to Chika meadow is doable solo.", "Guide ₹800–1,500/day"),
    ],
    checklist=[
        "Book Rohtang Pass NGT permit at rohtangpermits.nic.in (free, 2 days ahead)",
        "Carry altitude sickness tablets (Diamox) from a pharmacy before ascending",
        "Download offline HRTC bus schedule — connectivity drops above Kullu",
        "Pack a down jacket regardless of season — nights drop to 5°C even in July",
        "Check Manali–Leh highway status on HP Traffic Police Twitter before Leh plans",
    ],
    dos=[
        "Acclimatise for one full day in Manali before any high-altitude activity",
        "Stay in Old Manali or Vashisht for the best solo-female guesthouse culture",
        "Book treks only through registered agencies with ITBP-certified guides",
        "Carry ₹5,000+ in cash — ATMs in Lahaul-Spiti area frequently run out",
    ],
    donts=[
        "Trek alone above 3,000m without an acclimatisation day and a registered guide",
        "Ignore the 'road closed' signs on the Rohtang approach during monsoon",
        "Pay any middleman for Rohtang permits — they are free and online-only",
        "Drive rented bikes above Rohtang without proper gear and experience",
    ],
    budget={"backpacker": 2000, "midRange": 4500, "comfortable": 10000},
    emergency=[emg("Manali Police", "100"), emg("Women's Helpline", "1091"),
               emg("Kullu–Manali Hospital", "01902-252779"), emg("ITBP Emergency", "01902-252533")],
    premium=True,
    premium_preview="Premium covers: the 5 guesthouses in Old Manali rated safest by solo female travellers, exact Spiti Valley extension itinerary (Manali → Kaza → Chandratal, 7 days), monsoon-season alternatives when Rohtang is closed, and winter (Dec–Feb) Manali survival guide.",
    affiliates={"booking": "https://www.booking.com/searchresults.html?ss=Manali&aid=PLACEHOLDER",
                "worldNomads": "https://www.worldnomads.com/travel-insurance?affiliate=PLACEHOLDER"},
),

# 5 ── RISHIKESH ──────────────────────────────────────────────────────────────
card(
    "rishikesh-india", "Rishikesh", "both", "priya-kochi", 11,
    "https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=800&q=80",
    tldr=[
        "Rishikesh is the global yoga capital — but 30% of 'ashrams' are unregulated and target foreign women.",
        "Laxman Jhula bridge is the beating heart of the backpacker belt; stay within 1km of it.",
        "Bungee jumping and white-water rafting are legitimate and world-class here — use only registered operators.",
        "Most of the town is alcohol and meat free; this is a genuine religious city, not a performance.",
        "Monsoon (Jul–Sep): Ganges floods, rafting closed, ghats underwater — plan around this.",
    ],
    hoods=[
        hood("Laxman Jhula", 4, "Backpacker belt, cafés, yoga studios, shopping", True,
             "Best solo-female base. Walkable to most activities. German Bakery, Little Buddha Café."),
        hood("Ram Jhula / Swarg Ashram", 3, "Ashram-dense, religious, intense", False,
             "Beautiful but requires constant polite boundary-setting. Better as day visit from Laxman Jhula."),
        hood("Tapovan", 4, "Upscale yoga retreats, calm, riverside resorts", True,
             "For mid-range to premium stays. Quieter than Laxman Jhula. 5-min auto ride."),
    ],
    scams=[
        scm("Predatory yoga ashram / guru", "critical", "Ram Jhula area and online listings",
            "Unregistered 'guru' targets foreign women for extended retreat. Isolation, manipulation, financial drain.",
            "Research on forums (TripAdvisor, Lonely Planet Thorntree) before booking any retreat. Never pay more than 2 weeks upfront."),
        scm("Rafting overcharge and fake safety", "high", "Marine Drive rafting operators",
            "Unlicensed operator quotes ₹400 'discount' rafting; no safety briefing, no life jacket inspection.",
            "Use only TURA (Uttarakhand Rafting Association) registered operators. Ask for licence number. Min age/weight rules exist for safety."),
        scm("'Blessing' donation trap", "medium", "Ghats and temple entrances",
            "Priest offers forehead tilak or sacred thread; donation of ₹1,000–5,000 demanded before you can leave.",
            "Decline politely and firmly. No temple in Rishikesh charges for entry or mandates donations."),
    ],
    transport=[
        trn("Shared auto (Haridwar ↔ Rishikesh)", "Cheapest and most used. Runs constantly.", "₹40–80"),
        trn("Cycle rickshaw (within town)", "Best for navigating the narrow lanes of the ashram belt.", "₹30–80"),
        trn("AC bus (Delhi → Rishikesh)", "UPSRTC or private Volvo. 6–7 hours, comfortable.", "₹400–700"),
    ],
    gems=[
        gem("Beatles Ashram (Chaurasi Kutia)", "Abandoned ashram / street art", "Instagram but actually worth it",
            "Where the Beatles studied TM in 1968. Now an open ruin with excellent graffiti. Fee is worth it for the quiet.", "₹150 entry (foreigners ₹600)"),
        gem("Neer Garh Waterfall", "Waterfall trek", "45-min hike from Laxman Jhula",
            "Short jungle trek to a multi-tiered waterfall. Best on weekday mornings. Safe for solo.", "₹50 entry"),
        gem("Chotiwala restaurant (original)", "Legendary restaurant", "Split-location story",
            "The original 1958 restaurant has a rival next door with the same name. This one has the original costumed doorman on the left.", "Thali ₹180–300"),
    ],
    checklist=[
        "Research any yoga retreat or ashram on TripAdvisor and Lonely Planet Thorntree forums before booking",
        "Book white-water rafting with a TURA-registered operator (ask for licence number)",
        "Carry a scarf for temples and ashrams — exposed shoulders aren't welcome",
        "Pack mosquito repellent — riverside location means evening bites",
        "Check Ganges flood status if visiting June–September",
    ],
    dos=[
        "Stay in Laxman Jhula area for the best balance of safety and social vibe",
        "Book yoga classes at established studios (Sivananda, Parmarth Niketan) not street-tout pop-ups",
        "Attend the Parmarth Ganga Aarti at sunset — free, spectacular, and genuinely moving",
        "Use TURA-registered rafting operators even if they cost ₹200 more",
    ],
    donts=[
        "Pay more than 2 weeks upfront for any ashram or retreat programme",
        "Accept invitations to private 'meditation sessions' with individual gurus",
        "Raft with any operator who skips the safety briefing or life-jacket check",
        "Swim in the Ganges during or after monsoon — current is dangerous",
    ],
    budget={"backpacker": 1500, "midRange": 3500, "comfortable": 7500},
    emergency=[emg("Rishikesh Police", "100"), emg("Women's Helpline", "1091"),
               emg("AIIMS Rishikesh", "0135-2462941"), emg("Ambulance", "108")],
    premium=True,
    premium_preview="Premium covers: vetted list of 6 yoga retreats safe for solo foreign women (with red flags to watch for), the Rishikesh–Chopta–Tungnath trek guide (3 days, beginner-friendly), best riverside guesthouses with women-only floors, and a Haridwar day-trip add-on guide.",
    affiliates={"booking": "https://www.booking.com/searchresults.html?ss=Rishikesh&aid=PLACEHOLDER",
                "worldNomads": "https://www.worldnomads.com/travel-insurance?affiliate=PLACEHOLDER"},
),

# 6 ── DELHI ──────────────────────────────────────────────────────────────────
card(
    "delhi-india", "Delhi", "both", "leila-delhi", 15,
    "https://images.unsplash.com/photo-1587474135619-672929a8af76?w=800&q=80",
    tldr=[
        "Delhi Metro is your best friend — safe, AC, women-only coaches on every train.",
        "Old Delhi (Chandni Chowk) is overwhelming and scam-dense; go with a plan and leave by 6pm.",
        "Prepaid taxi booth inside IGI Airport arrivals is the only safe airport exit — ignore everyone else.",
        "Connaught Place touts will claim the tourist office is closed/moved; it is not — walk in yourself.",
        "South Delhi (Hauz Khas, Saket, Lodi Colony) is a different city — modern, safe, great food.",
    ],
    hoods=[
        hood("Hauz Khas / South Delhi", 5, "Cafés, boutiques, safe nights, metro access", True,
             "Best base for solo women. Hauz Khas Village has rooftop bars; Lodi Colony has street art and Green's Café."),
        hood("Paharganj", 2, "Budget hotel strip, backpacker chaos, near New Delhi station", False,
             "Cheap but high harassment and scam density. Only stay if you're catching an early train and need proximity."),
        hood("Connaught Place / CP", 3, "Commercial centre, heritage architecture, central", True,
             "Good for day visits. Underground metro-connected. High tout density; walk confidently and ignore everyone."),
    ],
    scams=[
        scm("Tourist office 'closed/moved' scam", "critical", "Connaught Place, New Delhi station",
            "Tout or friendly stranger claims India Tourism office is closed and offers to take you to a 'government-approved' travel agent.",
            "India Tourism Delhi office (88 Janpath) is open Mon–Fri 9am–6pm. Walk in yourself. Never follow strangers."),
        scm("Airport taxi tout", "high", "IGI Airport arrivals hall",
            "Aggressive men claim your pre-booked cab cancelled and offer cash rides. Overcharge ₹2,000–5,000.",
            "Use only the official Prepaid Taxi booth inside arrivals, or book Uber/Ola before landing and walk to the app-taxi pick-up zone."),
        scm("Gem export investment scam", "high", "Paharganj, Connaught Place",
            "Long con: 'businessman' offers you commission to carry gems as exports. Fake gems, real customs trouble.",
            "Never agree to carry anything for anyone. No legitimate gem exporter needs a tourist as a courier."),
        scm("Cycle rickshaw price switch", "medium", "Old Delhi, Paharganj",
            "Price agreed; demand doubles on arrival citing 'per person' or 'per bag' surcharges.",
            "State destination and total price before boarding. Confirm: 'This is the total, for both of us, for all bags.'"),
    ],
    transport=[
        trn("Delhi Metro", "Safest and fastest. Women-only coach (first coach, marked pink) on every line.", "₹10–60 per journey"),
        trn("Uber / Ola", "Both fully operational in Delhi. Preferred for night journeys.", "₹80–300 within city"),
        trn("Prepaid taxi (IGI Airport)", "Official booth inside T2/T3 arrivals. Fixed fares, no negotiation.", "₹400–700 to central Delhi"),
    ],
    gems=[
        gem("Lodi Garden at sunrise", "Heritage park", "Secret morning Delhi",
            "Mughal-era tombs inside a manicured park. At 7am: joggers, silence, photogenic mist. Zero touts.", "Free entry"),
        gem("Hauz Khas Complex (village end)", "Ruins + lake", "Medieval deer park",
            "14th-century madrasa and tomb above a deer park lake. End of Hauz Khas Village — walk through the boutiques to reach it.", "Free"),
        gem("Paranthe Wali Gali, Chandni Chowk", "Street food lane", "The only tourist trap worth it",
            "145-year-old lane of stuffed paratha shops. Genuinely delicious. Agree price before sitting down.", "₹80–150 per paratha"),
    ],
    checklist=[
        "Download Delhi Metro app and top up a Metro Smart Card on arrival",
        "Book airport transfer via Uber/Ola app before landing — prepaid taxi as backup",
        "Save India Tourism Delhi helpline: 1800-111-363 (free, English)",
        "Check air quality index (AQI Delhi) before travel — Nov–Jan can be severe",
        "Book Agra day-trip train (Gatimaan Express or Shatabdi) on IRCTC app in advance",
    ],
    dos=[
        "Use the metro women-only coach for every journey — it is safe and enforced",
        "Walk into India Tourism office on Janpath yourself; ignore all claims it is closed",
        "Explore Lodi Colony street art and Lodi Garden as a morning pair",
        "Eat at Karim's in Old Delhi for lunch — old establishment, table service, safe",
    ],
    donts=[
        "Follow any stranger who claims to be a 'student' wanting to practice English",
        "Accept auto or taxi rides from touts inside the airport arrivals hall",
        "Walk Paharganj lanes alone after dark",
        "Agree to carry any package or parcel for anyone, however friendly they seem",
    ],
    budget={"backpacker": 1800, "midRange": 4000, "comfortable": 9000},
    emergency=[emg("Delhi Police", "100"), emg("Women's Helpline", "1091"),
               emg("India Tourism Delhi", "1800-111-363"), emg("Ambulance", "108")],
    affiliates={"booking": "https://www.booking.com/searchresults.html?ss=Delhi&aid=PLACEHOLDER",
                "worldNomads": "https://www.worldnomads.com/travel-insurance?affiliate=PLACEHOLDER",
                "airalo": "https://www.airalo.com/india-esim?ref=PLACEHOLDER"},
),

# 7 ── AGRA ───────────────────────────────────────────────────────────────────
card(
    "agra-india", "Agra", "both", "sara-berlin", 10,
    "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80",
    tldr=[
        "Taj Mahal at sunrise (gates open 6am) means 90 minutes of soft light before bus tours arrive.",
        "Agra Fort and Fatehpur Sikri are world-class and almost always skipped — don't skip them.",
        "Agra is a 2-night city maximum; most people do it as a Golden Triangle stop, not a base.",
        "The area around Taj Mahal's south gate is the highest scam-density zone in India.",
        "Book Taj Mahal tickets on the ASI India website the night before — gate tickets sell out.",
    ],
    hoods=[
        hood("Taj Ganj (south gate area)", 2, "Closest to Taj, maximum tout density", False,
             "Budget hotels here but you'll run a gaunt of scams every time you step outside. Stay in Sadar Bazaar instead."),
        hood("Sadar Bazaar", 4, "Lively market area, better hotels, 10 min to Taj", True,
             "Best balance of convenience and calm. Dasaprakash for South Indian food; Pind Balluchi for North Indian."),
    ],
    scams=[
        scm("Fake Taj Mahal ticket office", "critical", "South gate approach road",
            "Official-looking 'ticket office' sells counterfeit tickets. You pay twice at the real gate.",
            "Buy only at official ASI booth at the gate, or online at asi.payumoney.com the night before."),
        scm("Marble inlay 'factory' commission", "high", "Agra-wide, tout-assisted",
            "Rickshaw takes you to 'government marble workshop'. Overpriced souvenirs with heavy sales pressure.",
            "Genuine marble inlay artisans sell in Sadar Bazaar at half the price with no commission markup."),
        scm("Auto-rickshaw price flip", "medium", "Outside Taj gates",
            "₹100 agreed for return ride; ₹500 demanded on return citing 'waiting time'.",
            "Agree total return price including waiting before departing. Use Uber/Ola if available."),
    ],
    transport=[
        trn("Tonga (horse carriage) or e-rickshaw", "Mandatory for Taj Mahal approach — no petrol vehicles within 500m.", "₹50–150"),
        trn("Uber / Ola", "Available in Agra. Best for Agra Fort ↔ Taj ↔ Fatehpur Sikri day-loop.", "₹100–400"),
        trn("Gatimaan Express (Delhi → Agra)", "Fastest train, 1h35m. Book on IRCTC 60 days ahead.", "₹750 (AC chair car)"),
    ],
    gems=[
        gem("Taj Mahal at sunrise, west gate", "UNESCO monument", "Fewer crowds than south gate",
            "West gate (Shilpgram entrance) has shorter queues than south gate. Book west-gate tickets.", "₹1,100 (foreigners); ₹50 (Indian)"),
        gem("Mehtab Bagh at sunset", "Mughal garden", "Taj reflection view",
            "Garden directly north of Taj across the river. Perfect Taj reflection in the water tank at sunset. Almost no crowds.", "₹300 entry"),
        gem("Agra Fort inner zenana", "Fort", "Often missed by day-trippers",
            "The women's quarters (zenana) inside Agra Fort have the best Taj view in existence — from Shah Jahan's prison cell.", "₹650 (foreigners); ₹40 (Indian)"),
    ],
    checklist=[
        "Book Taj Mahal tickets online at asi.payumoney.com the evening before",
        "Set alarm for 5:30am — Taj gates open 6am and sunrise light is 6:30–8am",
        "Book Gatimaan Express or Shatabdi on IRCTC app well in advance",
        "Carry exact change for e-rickshaw to Taj south gate (₹50–100)",
        "Pack sunscreen and a hat — Agra has zero shade between sites",
    ],
    dos=[
        "Enter via west gate for shorter queues, same monument",
        "Visit Agra Fort the afternoon of arrival — it is genuinely spectacular and always uncrowded",
        "Buy marble souvenirs from Sadar Bazaar artisans, not commission shops",
        "Do Mehtab Bagh at sunset as your last activity — it is free of touts",
    ],
    donts=[
        "Buy Taj tickets from any booth on the approach road — official only",
        "Accept free marigold garlands or 'blessings' outside the Taj gates",
        "Agree to an auto return price that isn't fixed before you depart",
        "Skip Fatehpur Sikri — it is 40km away and completely worth the detour",
    ],
    budget={"backpacker": 1500, "midRange": 3500, "comfortable": 8000},
    emergency=[emg("Agra Police", "100"), emg("Women's Helpline", "1091"),
               emg("Tourist Police Agra", "0562-2421204"), emg("Ambulance", "108")],
    affiliates={"booking": "https://www.booking.com/searchresults.html?ss=Agra&aid=PLACEHOLDER",
                "worldNomads": "https://www.worldnomads.com/travel-insurance?affiliate=PLACEHOLDER"},
),

# 8 ── MUMBAI ─────────────────────────────────────────────────────────────────
card(
    "mumbai-india", "Mumbai", "both", "ananya-mumbai", 13,
    "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800&q=80",
    tldr=[
        "Mumbai local trains have women-only coaches — use them; the general coaches during peak hour are not safe.",
        "Mumbai is India's safest major city for solo women at night, but marine drive after midnight is still solo-avoid.",
        "Taxis (black-and-yellow) are metered and honest here; Uber/Ola also fully operational.",
        "Colaba Causeway is pick-pocket central — use a crossbody bag with the clasp facing inward.",
        "Dharavi is a thriving urban township, not a tragedy — the Reality Tours guided visit is genuinely excellent.",
    ],
    hoods=[
        hood("Bandra West", 5, "Trendy, safe, restaurants, nightlife, sea link views", True,
             "Best solo-female base in Mumbai. Carter Road, Hill Road, Linking Road. Metro and local train access."),
        hood("Colaba", 4, "Heritage, Taj hotel, cafés, tourist belt", True,
             "Gateway of India, Leopold Café, Mondegar. Tourist-dense but safe. Pick-pocket aware at Causeway market."),
        hood("Juhu / Andheri West", 4, "Airport-close, Bollywood adjacent, beach", True,
             "Good for transit stays near airport. Juhu Beach at sunset is pleasant; skip after 9pm."),
    ],
    scams=[
        scm("Colaba Causeway pick-pockets", "medium", "Colaba Causeway market",
            "Deliberate jostling in the narrow market lanes; wallet or phone lifted in the crowd.",
            "Crossbody bag, clasp facing your body. Phone in front pocket. Don't pull out wallet in the market."),
        scm("Taxi meter 'broken' scam", "medium", "Airport exits, Colaba",
            "Driver claims meter is broken and quotes fixed (inflated) fare.",
            "All Mumbai black-and-yellow taxis must use meters. If it's 'broken', take another cab or use Uber."),
        scm("Gateway of India boat 'tour'", "medium", "Gateway of India pier",
            "Unlicensed boat operators quote ₹200 for Elephanta ferry; takes you on an unscheduled 'tour' instead.",
            "Buy Elephanta Island ferry tickets only at the MTDC booth on the pier — orange, official signage."),
    ],
    transport=[
        trn("Mumbai local train (women's coach)", "First coach from Western Line; marked with a 'W'. Safe, fast, ₹5–20.", "₹5–20"),
        trn("Uber / Ola", "Fully operational. Better than autos for cross-city journeys.", "₹100–400"),
        trn("Black-and-yellow taxi", "Metered, reliable, iconic. Insist on meter — drivers almost always comply.", "₹30–200"),
    ],
    gems=[
        gem("Dhobi Ghat viewing platform", "Urban landmark", "Best at 8am",
            "The world's largest open-air laundry. Watch from the bridge on Dr E Moses Road. Zero touts, surprisingly meditative.", "Free"),
        gem("Dharavi township tour (Reality Tours)", "Guided urban experience", "Ethical and eye-opening",
            "80% of profits go to Dharavi community projects. The best urban sociology experience in India. Book in advance.", "₹700–1,200"),
        gem("Worli Sea Face at sunset", "Promenade", "Local Mumbai, not tourist",
            "Less crowded than Marine Drive. Sea Link views. Locals jog here; safe, pleasant, real Mumbai.", "Free"),
    ],
    checklist=[
        "Download Mumbai local train map offline — Western, Central, and Harbour lines",
        "Book Elephanta Island ferry at MTDC pier booth, not from touts",
        "Save Mumbai Police helpline: 100 and Women's helpline: 103",
        "Check monsoon dates — July–August, Mumbai floods badly and local trains halt",
        "Carry a small crossbody bag for Colaba Causeway shopping",
    ],
    dos=[
        "Use the women's coach on all local train journeys — it is safe and air-conditioned on newer trains",
        "Eat at Britannia & Co in Ballard Estate — 100-year-old Irani café, unmissable berry pulao",
        "Walk Marine Drive at sunrise for the best crowd-free Gateway view",
        "Take the Reality Tours Dharavi visit — context changes everything",
    ],
    donts=[
        "Travel in general coach of local trains during 8–10am or 5–8pm peak hours",
        "Buy Elephanta ferry tickets from anyone other than the official MTDC booth",
        "Leave valuables in your hotel room — use the safe or carry them",
        "Dismiss Dharavi as unsafe — it is a working township and the tour is genuinely safe",
    ],
    budget={"backpacker": 2500, "midRange": 5000, "comfortable": 12000},
    emergency=[emg("Mumbai Police", "100"), emg("Women's Helpline", "103"),
               emg("Tourist Helpline", "1800-22-1363"), emg("Ambulance", "108")],
    affiliates={"booking": "https://www.booking.com/searchresults.html?ss=Mumbai&aid=PLACEHOLDER",
                "worldNomads": "https://www.worldnomads.com/travel-insurance?affiliate=PLACEHOLDER"},
),

# 9 ── BANGALORE ──────────────────────────────────────────────────────────────
card(
    "bangalore-india", "Bangalore", "both", "riya-bangalore", 10,
    "https://images.unsplash.com/photo-1596176530799-ede15e49ada9?w=800&q=80",
    tldr=[
        "Bangalore is India's most liveable city for solo women — the tech culture genuinely shifts the baseline.",
        "Namma Metro (Purple + Green lines) is excellent; women-only coach in every train.",
        "MG Road and Brigade Road are the tourist belts; Indiranagar and Koramangala are where locals actually go.",
        "Traffic is brutal — build 2× the expected travel time into any schedule.",
        "The microbrewery scene here is world-class and solo-female-comfortable; Arbor is the benchmark.",
    ],
    hoods=[
        hood("Indiranagar", 5, "Cafés, craft beer, boutiques, young crowd, metro-connected", True,
             "The solo-female ideal base. 100 Feet Road for food and nightlife; safe auto culture."),
        hood("Koramangala", 5, "Startup district, restaurants, 24-hour cafés", True,
             "Great food at all price points. Social is the best microbrewery. Well-lit streets, Uber always available."),
        hood("MG Road / Brigade Road", 3, "Commercial, hotel strip, tourist-adjacent", False,
             "Fine for transit; hotels here are expensive and the neighbourhood is more chaotic than Indiranagar."),
    ],
    scams=[
        scm("Airport taxi overcharge", "medium", "KIA Airport exits",
            "Touts quote ₹1,500–2,500 for city-centre rides; KIAS pre-paid is ₹700–900.",
            "Use KIAS pre-paid taxi counter inside arrivals, or book Uber/Ola before landing."),
        scm("MG Road gem store", "medium", "MG Road / Commercial Street",
            "Same gem commission chain as Jaipur but less common. Friendly stranger leads to 'export store'.",
            "Ignore unsolicited guided shopping from strangers. Shop independently in Chickpete wholesale market."),
    ],
    transport=[
        trn("Namma Metro", "Purple and Green lines cover most tourist areas. Women-only coach, first in train.", "₹10–55"),
        trn("Uber / Ola / Rapido", "All three fully operational. Rapido bike-taxi cheapest for short hops.", "₹50–250"),
        trn("BMTC Volvo AC bus", "Covers routes metro doesn't. Route 500-series covers airport.", "₹5–50"),
    ],
    gems=[
        gem("Arbor Brewing Company, Indiranagar", "Microbrewery", "Benchmark Bangalore craft beer",
            "The craft beer that started the Bangalore microbrewery scene. Solo-female comfortable, excellent food.", "Beer ₹400–600; meal ₹600–1,200"),
        gem("ISKCON Temple, Rajajinagar", "Temple complex", "Spectacular Hare Krishna campus",
            "Massive, calm, beautifully maintained temple complex. Free entry, no touts, good prasadam meals.", "Free entry; meal ₹50–100"),
        gem("Cubbon Park morning walk", "Urban park", "Local Bangalore morning ritual",
            "150-year-old park in the city centre. 8am: joggers, dogs, families. Safe for solo women at all daylight hours.", "Free"),
    ],
    checklist=[
        "Download Namma Metro app and top up a Bangalore Metro smart card",
        "Book hotel in Indiranagar or Koramangala, not MG Road corridor",
        "Save Bangalore Women's Helpline: 1091 and Police: 100",
        "Allow extra travel time — Bangalore traffic is genuinely bad at 9am and 6pm",
        "Book Coorg or Chikmagalur day trip through a registered tour operator if extending trip",
    ],
    dos=[
        "Base yourself in Indiranagar for the best solo-female food and café culture",
        "Use Namma Metro for all metro-connected journeys — faster than road always",
        "Visit ISKCON Temple at 7am for the morning aarti — peaceful and crowd-free",
        "Eat at MTR (Mavalli Tiffin Room) in Lalbagh for the authentic Bangalore breakfast experience",
    ],
    donts=[
        "Accept cab rides from touts at KIA Airport — use the pre-paid counter or app",
        "Plan more than 3 sights in a day — traffic will defeat you",
        "Miss the microbrewery belt in Indiranagar/Koramangala for at least one evening",
        "Ignore the day-trip options — Coorg, Chikmagalur, and Hampi are all reachable",
    ],
    budget={"backpacker": 2000, "midRange": 4500, "comfortable": 10000},
    emergency=[emg("Bangalore Police", "100"), emg("Women's Helpline", "1091"),
               emg("Namma Metro helpline", "080-22969999"), emg("Ambulance", "108")],
    affiliates={"booking": "https://www.booking.com/searchresults.html?ss=Bangalore&aid=PLACEHOLDER"},
),

# 10 ── KOLKATA ────────────────────────────────────────────────────────────────
card(
    "kolkata-india", "Kolkata", "both", "leila-delhi", 8,
    "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    tldr=[
        "Kolkata is one of India's safest cities for solo women — the street culture is genuinely different.",
        "The Metro is clean, safe, and has women-only coaches; yellow taxis are metered and reliable.",
        "Park Street is the nightlife and café spine; Ballygunge and Lake Road are the best residential bases.",
        "Howrah Bridge at dawn (6–7am) is one of the most photogenic 20 minutes in India — and there are almost no touts.",
        "Budget ₹3–4 days: Kumartuli potters' quarter and New Market are completely off most tourist itineraries.",
    ],
    hoods=[
        hood("Ballygunge / Lake Road", 5, "Residential, safe, cafés, easy Metro access", True,
             "Best solo-female base. Quiet tree-lined streets, excellent food at all price points, feels like old Calcutta."),
        hood("Park Street", 4, "Restaurants, cafés, colonial architecture, nightlife", True,
             "Flurys for breakfast, Peter Cat for dinner. Well-lit evenings. Safe for solo dining and walking."),
        hood("Sudder Street (backpacker belt)", 3, "Budget hotels, tourist-adjacent, central", False,
             "Functional and cheap but scruffier than Ballygunge. Fine as a base; just less pleasant to walk around."),
    ],
    scams=[
        scm("Howrah station taxi overcharge", "medium", "Howrah and Sealdah stations",
            "Unofficial taxis cluster at exits; quote 3× meter rates to confused arrivals.",
            "Walk to the prepaid taxi booth inside both stations. Kolkata yellow taxis outside also use meters — insist."),
        scm("New Market 'closed today' redirect", "medium", "New Market entrance, Esplanade",
            "Tout claims New Market is closed for a holiday and offers to take you to a 'better' market (his commission shop).",
            "New Market is almost never closed. Walk past the tout and enter yourself."),
        scm("Fake donation for Mother Teresa's home", "medium", "Near Kalighat",
            "Man with official-looking clipboard solicits 'donations' for Missionaries of Charity.",
            "Missionaries of Charity does not collect street donations. Donate only on their official website."),
    ],
    transport=[
        trn("Kolkata Metro", "Blue Line covers Park Street to Howrah. Women-only coach, first in train.", "₹5–30"),
        trn("Yellow Ambassador taxi (metered)", "Iconic and honest. Insist on meter — drivers comply.", "₹30–150"),
        trn("Uber / Ola", "Available; useful for areas not on Metro. App fares are fair.", "₹80–250"),
    ],
    gems=[
        gem("Kumartuli potters' quarter", "Artisan neighbourhood", "Off tourist radar",
            "Where all of Kolkata's Durga Puja idols are made year-round. Clay sculptors working in tiny workshops. No touts, no entry fee.", "Free"),
        gem("Flurys, Park Street", "Heritage café", "1927 institution",
            "Tea room open since 1927. Solo breakfast with pastries and filter coffee. Safe, civilised, excellent.", "Breakfast ₹400–700"),
        gem("Princep Ghat at sunset", "Colonial ghat", "Quiet riverside",
            "Victorian memorial arch on the Hooghly. Locals come for evening walks. Boats for hire. Almost no tourists.", "Free; boat ₹100–200"),
    ],
    checklist=[
        "Book hotel in Ballygunge or near Park Street, not Sudder Street if budget allows",
        "Download Kolkata Metro app and buy a Metro smart card at any station",
        "Check Durga Puja dates (October) — if visiting during festival, book months ahead",
        "Carry ₹500 in small change for yellow taxi meters and street food",
        "Save Kolkata Police helpline: 100 and Women's helpline: 1091",
    ],
    dos=[
        "Eat at Kewpie's in Elgin for authentic Bengali home cooking — book ahead",
        "Walk Howrah Bridge from the Kolkata side at 6am for zero crowds and best light",
        "Visit Kumartuli on a weekday morning — sculptors are at work and welcoming",
        "Use yellow Ambassador taxis — they are metered, honest, and a Kolkata experience",
    ],
    donts=[
        "Accept rides from anyone approaching you at Howrah or Sealdah station exits",
        "Give money to anyone collecting for Missionaries of Charity on the street",
        "Miss the Sunday morning book market on College Street — largest second-hand book market in the world",
        "Rush Kolkata — it rewards slow travel more than almost any Indian city",
    ],
    budget={"backpacker": 1500, "midRange": 3500, "comfortable": 8000},
    emergency=[emg("Kolkata Police", "100"), emg("Women's Helpline", "1091"),
               emg("Tourist Police Kolkata", "033-22143004"), emg("Ambulance", "108")],
    affiliates={"booking": "https://www.booking.com/searchresults.html?ss=Kolkata&aid=PLACEHOLDER"},
),

# 11 ── CHENNAI ────────────────────────────────────────────────────────────────
card(
    "chennai-india", "Chennai", "both", "kavya-chennai", 9,
    "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    tldr=[
        "Chennai has the best South Indian food in the world — if you leave without eating a proper tiffin breakfast, you have failed.",
        "Marina Beach is the world's second-longest urban beach; it is safe at sunrise, avoid after sunset.",
        "Auto-rickshaws here notoriously refuse meters — use Uber/Ola or negotiate firmly before boarding.",
        "The MRTS and Chennai Metro together cover most tourist areas; women-only coach on Metro.",
        "Mylapore is the cultural and religious heart of the city — older, calmer, and more authentic than T Nagar.",
    ],
    hoods=[
        hood("Mylapore", 5, "Temple culture, old Madras, filter coffee, silk sarees", True,
             "Best solo-female base. Kapaleeshwarar Temple, Luz Church, cycle-rickshaw lanes. Morning filter coffee ritual."),
        hood("Nungambakkam / Egmore", 4, "Hotels, Metro access, restaurants, central", True,
             "Practical base with good mid-range hotels. Saravana Bhavan HQ is here — eat there."),
        hood("T Nagar", 3, "Shopping, silk, crowds, congested", False,
             "Great for silk and jewellery shopping but extremely crowded. Stay only if that's your primary purpose."),
    ],
    scams=[
        scm("Auto meter refusal", "high", "City-wide",
            "Autos quote 2–3× Uber rates and refuse to use meters, especially from airport and Central Station.",
            "Use Uber or Ola exclusively in Chennai. If you must use auto, get Ola Auto — it's app-metered."),
        scm("Silk 'wholesale' store redirect", "medium", "T Nagar and tourist areas",
            "Friendly local offers to show you the 'real' silk shop where 'only locals go'. Commission-based.",
            "Buy silk independently at Co-optex (government textile store, fixed prices) on Anna Salai."),
        scm("Marina Beach photography harassment", "medium", "Marina Beach",
            "Groups of young men photograph women without consent; camera pointed at face/body.",
            "Sunrise hours (6–8am) are peaceful. Avoid evenings. If photographed without consent, confront directly or walk to nearest police booth."),
    ],
    transport=[
        trn("Chennai Metro", "Green and Blue lines. Women-only coach. Covers airport to central.", "₹10–60"),
        trn("Uber / Ola", "Essential in Chennai — auto meters are unreliable. Use app-based always.", "₹80–300"),
        trn("MRTS (suburban rail)", "Covers coastal corridor from Beach to Velachery. Cheap and fast.", "₹5–20"),
    ],
    gems=[
        gem("Murugan Idli Shop, Mylapore", "Tiffin restaurant", "The Chennai breakfast benchmark",
            "Open since 1969. Idli, sambar, chutney. The standard against which all South Indian breakfast is measured. Queue moves fast.", "Breakfast ₹80–150"),
        gem("Kapaleeshwarar Temple at dawn", "Temple complex", "600-year-old Dravidian architecture",
            "The best Dravidian gopuram in Tamil Nadu accessible without a day trip. 6am: priests, flowers, no tourists.", "Free for Hindus; non-Hindus welcome in outer courtyard"),
        gem("Cholamandal Artists' Village", "Artist colony", "Largest in Asia",
            "Living artist community 20km south of Chennai. Galleries, studios, sculpture garden. Completely overlooked by tourists.", "Free entry; gallery ₹50"),
    ],
    checklist=[
        "Book hotel in Mylapore or Nungambakkam — not T Nagar unless shopping is the focus",
        "Download Uber/Ola before arrival — auto meter situation makes apps essential",
        "Visit Murugan Idli Shop before 9am on your first morning",
        "Check Pongal festival dates (January) if visiting in winter — major and beautiful",
        "Carry a dupatta for temple visits — shoulders must be covered",
    ],
    dos=[
        "Eat tiffin breakfast (idli/vada/dosa) at a proper Mylapore restaurant on day one",
        "Visit Kapaleeshwarar Temple at dawn — the 6am rituals are stunning",
        "Use Uber/Ola for all transport — saves the daily auto negotiation frustration",
        "Go to Cholamandal Artists' Village if you have a half-day to spare",
    ],
    donts=[
        "Negotiate with autos outside Central Station or the airport — use app always",
        "Visit Marina Beach alone after 7pm",
        "Buy silk from any shop you were taken to by an auto driver or 'friendly local'",
        "Skip the filter coffee — it is a defining Chennai experience and costs ₹20",
    ],
    budget={"backpacker": 1800, "midRange": 4000, "comfortable": 9000},
    emergency=[emg("Chennai Police", "100"), emg("Women's Helpline", "1091"),
               emg("Tourist Helpline Tamil Nadu", "1800-425-4747"), emg("Ambulance", "108")],
    affiliates={"booking": "https://www.booking.com/searchresults.html?ss=Chennai&aid=PLACEHOLDER"},
),

# 12 ── UDAIPUR ────────────────────────────────────────────────────────────────
card(
    "udaipur-india", "Udaipur", "both", "sara-berlin", 11,
    "https://images.unsplash.com/photo-1588083949709-a82cad48aed7?w=800&q=80",
    tldr=[
        "Udaipur is Rajasthan's most romantic and solo-female-comfortable city — the pace is slower, the touts fewer.",
        "Lake Pichola at sunset from a rooftop café is one of India's iconic experiences — and it is free.",
        "Book heritage havelis in the old city for the view; book modern hotels in New City for the amenities.",
        "The boat ride to Jag Mandir (not Lake Palace, which is hotel-only) is worth every rupee.",
        "Holi in Udaipur (March) is internationally famous; solo women should visit with a group or organised event.",
    ],
    hoods=[
        hood("Old City (Lake Pichola side)", 4, "Heritage havelis, rooftop cafés, lake views", True,
             "Best atmosphere. Walk to City Palace, Jagdish Temple. Rooftop restaurants with lake views are everywhere."),
        hood("Fateh Sagar Lake area", 4, "Local Udaipur, less touristy, evening promenade", True,
             "Where locals go in the evenings. Nehru Park island, ice cream stalls, quiet. Good mid-range hotels."),
    ],
    scams=[
        scm("Lake Palace boat ticket fraud", "medium", "Lake Pichola ghats",
            "Touts sell 'boat tickets to Lake Palace'. Lake Palace is a private Taj hotel — public boats go to Jag Mandir only.",
            "Book RTDC boat tickets at the official booth at Rameshwar Ghat only. Jag Mandir is the correct destination."),
        scm("Miniature painting 'artist' commission", "medium", "Old City lanes",
            "Artist invites you to watch him paint, then sells at inflated prices with social pressure to buy.",
            "Genuine miniature painting workshops exist (Shilpgram craft village). Browse independently; prices are fixed."),
        scm("Sunset rooftop 'cover charge'", "low", "Lake-view restaurants",
            "Minimum spend of ₹500–1,000 per person imposed only when bill arrives, not when seated.",
            "Ask explicitly about minimum spend before sitting. Most honest places display it on the menu."),
    ],
    transport=[
        trn("Auto-rickshaw", "Metered in Udaipur; drivers are generally more honest than Jaipur or Chennai.", "₹30–150"),
        trn("Uber / Ola", "Available and reliable. Best for airport and day trips to Haldighati.", "₹100–300"),
        trn("Cycle hire", "Old City is compact and flat enough for cycling. Hire from most guesthouses.", "₹100–200/day"),
    ],
    gems=[
        gem("Bagore Ki Haveli museum", "Heritage haveli", "Best folk art collection in Rajasthan",
            "18th-century haveli on the lake with 138 rooms of folk costumes, puppets, and daily cultural performances at 7pm.", "₹60 entry; show ₹100"),
        gem("Shilpgram craft village", "Artisan village", "Fixed-price genuine crafts",
            "Rural arts and crafts complex, 3km west of city. No commission touts. Miniature painting, block printing, pottery.", "₹30 entry"),
        gem("Fateh Sagar at sunset", "Lake promenade", "Local Udaipur evening",
            "The lake Udaipuris actually use. Boat rides, island park, kulfi stalls. Completely tourist-free.", "Boat ₹30–100"),
    ],
    checklist=[
        "Book lake-view haveli in Old City 2–3 months ahead for peak season (Oct–Mar)",
        "Buy RTDC boat tickets at Rameshwar Ghat booth only — not from touts",
        "Pack a light cardigan — Udaipur evenings are cool October through February",
        "Check Holi dates if visiting March — book a structured event for solo travel",
        "Carry ₹200 exact change for Jagdish Temple boat and Bagore Ki Haveli entry",
    ],
    dos=[
        "Watch the sunset from Ambrai Ghat — free, no minimum spend, the best lake view",
        "Visit Bagore Ki Haveli for the 7pm folk performance — it is genuinely excellent",
        "Explore Shilpgram for honest fixed-price Rajasthani crafts",
        "Hire a cycle for Old City — it is the best way to discover the lanes",
    ],
    donts=[
        "Buy boat tickets to 'Lake Palace' from touts — public boats go to Jag Mandir only",
        "Sit down at a lake-view restaurant without confirming the minimum spend",
        "Visit Monsoon Palace (Sajjangarh) without checking opening times — it closes early",
        "Rush out of Udaipur — it is one of the rare Indian cities that rewards an extra day",
    ],
    budget={"backpacker": 1800, "midRange": 4000, "comfortable": 10000},
    emergency=[emg("Udaipur Police", "100"), emg("Women's Helpline", "1091"),
               emg("Tourist Police Udaipur", "0294-2411535"), emg("Ambulance", "108")],
    affiliates={"booking": "https://www.booking.com/searchresults.html?ss=Udaipur&aid=PLACEHOLDER"},
),

# 13 ── KOCHI ──────────────────────────────────────────────────────────────────
card(
    "kochi-india", "Kochi", "both", "priya-kochi", 12,
    "https://images.unsplash.com/photo-1576186614082-7162e8a1b25d?w=800&q=80",
    tldr=[
        "Fort Kochi is one of India's most solo-female-comfortable neighbourhoods — slow, walkable, art-filled.",
        "The Chinese fishing nets at dawn are the classic image but the light is only good 6:30–8am.",
        "Kathakali and Kalaripayattu performances in Fort Kochi are tourist-facing but genuinely excellent.",
        "Kerala backwaters day cruise (Alleppey/Alappuzha, 90km south) is the most-recommended solo add-on.",
        "Monsoon season (June–August) is hot and very wet — but Kochi stays open and is half the price.",
    ],
    hoods=[
        hood("Fort Kochi", 5, "Colonial heritage, cafés, art galleries, Chinese nets", True,
             "The entire solo-travel reason to come to Kochi. Princess Street is the spine. Walkable, safe, excellent food."),
        hood("Mattancherry", 4, "Spice warehouses, Jewish quarter, antique shops", True,
             "20-min walk or ₹30 auto from Fort Kochi. Paradesi Synagogue, Dutch Palace, spice market. Very safe."),
        hood("Ernakulam (mainland)", 3, "Commercial, transport hub, modern", False,
             "Where the buses and trains are. Fine for transit; no reason to base yourself here if Fort Kochi has rooms."),
    ],
    scams=[
        scm("Kathakali 'donation' after performance", "low", "Fort Kochi performance venues",
            "Performers pass a collection box post-show and create social pressure for large amounts.",
            "Fixed-price ticket covers the performance. Tip generously if moved but ₹100–200 is appropriate — not ₹1,000."),
        scm("Spice shop overcharge, Mattancherry", "medium", "Mattancherry spice district",
            "Shops near the synagogue quote tourist prices 5–10× the real wholesale rate.",
            "Shops 2–3 streets back from the main synagogue lane have honest prices. Compare at 3 shops before buying."),
        scm("Auto overcharge, Ernakulam", "medium", "Ernakulam ferry terminal, railway station",
            "Autos at transport hubs refuse meters and quote flat rates to Fort Kochi ferry.",
            "Take the government ferry from Ernakulam to Fort Kochi (₹5) — faster and infinitely more scenic than any auto."),
    ],
    transport=[
        trn("Government ferry (Ernakulam ↔ Fort Kochi)", "₹5 and a 15-minute scenic harbour crossing. Best transport in Kochi.", "₹5"),
        trn("Auto-rickshaw within Fort Kochi", "Short distances only. Agree price before; ₹50–100 most rides.", "₹50–120"),
        trn("Cycle hire", "Fort Kochi is flat and compact. Most guesthouses rent bikes.", "₹100–150/day"),
    ],
    gems=[
        gem("Kashi Art Café, Fort Kochi", "Art gallery + café", "The original Fort Kochi institution",
            "Gallery and café since 1997. Solo breakfast with rotating contemporary art on the walls. The most civilised morning in Kerala.", "Breakfast ₹300–500"),
        gem("Kerala Folklore Museum, Ernakulam", "Museum", "Largest in Kerala, almost no tourists",
            "Three floors of masks, costumes, murals, and ritual objects. Extraordinary collection; entry is never crowded.", "₹300 entry"),
        gem("Alleppey backwaters day cruise", "Backwaters experience", "Non-negotiable add-on",
            "90km south. Government DTPC boat (₹400, half-day) or private houseboat. The single best day trip in South India.", "DTPC cruise ₹400; private houseboat from ₹3,500"),
    ],
    checklist=[
        "Book Fort Kochi guesthouse on Princess Street or Burgher Street 2+ months ahead in peak season",
        "Check ferry timings from Ernakulam Boat Jetty — last ferry is around 9:30pm",
        "Book Alleppey backwaters day cruise through DTPC Kochi or your guesthouse",
        "Carry a light rain jacket October through May — Kerala gets unexpected showers",
        "Save Kerala Tourist Police helpline: 1800-425-4747",
    ],
    dos=[
        "Arrive at Chinese fishing nets by 6:30am for the best light and fewest people",
        "Take the government ferry between Ernakulam and Fort Kochi — ₹5 and spectacular",
        "Attend a Kathakali performance at Kerala Kathakali Centre (best in Fort Kochi)",
        "Walk the full Mattancherry-to-Fort Kochi coastal path in the early morning",
    ],
    donts=[
        "Buy spices from the first shop near the Paradesi Synagogue — walk deeper into the lanes",
        "Skip Alleppey if you have even one extra day — the backwaters are the whole point of Kerala",
        "Miss the Kochi–Muziris Biennale if visiting in December–February — one of Asia's best art events",
        "Take an auto where the government ferry goes — it is slower, more expensive, and less beautiful",
    ],
    budget={"backpacker": 1800, "midRange": 4000, "comfortable": 9000},
    emergency=[emg("Kochi Police", "100"), emg("Women's Helpline", "1091"),
               emg("Tourist Police Kerala", "1800-425-4747"), emg("Ambulance", "108")],
    affiliates={"booking": "https://www.booking.com/searchresults.html?ss=Kochi&aid=PLACEHOLDER"},
),

