-- 014: trip_submissions table + seed 12 existing mock trips

create table trip_submissions (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid references auth.users on delete set null,
  contributor_slug text,
  destination_slug text not null,
  destination      text not null,
  trip_start       date not null,
  trip_end         date not null,
  day_count        int not null,
  total_cost_inr   int not null,
  total_cost_usd   int not null,
  cost_stay        int not null default 0,
  cost_food        int not null default 0,
  cost_transport   int not null default 0,
  cost_activities  int not null default 0,
  cost_misc        int not null default 0,
  top_notes        jsonb not null default '[]',
  highlight        text not null,
  status           text not null default 'pending'
                   check (status in ('pending', 'approved', 'rejected')),
  created_at       timestamptz not null default now()
);

alter table trip_submissions enable row level security;

create policy "Anyone reads approved trips" on trip_submissions
  for select using (status = 'approved');

create policy "Users insert own trips" on trip_submissions
  for insert with check (auth.uid() = user_id);

-- Seed existing 12 trips as approved

INSERT INTO trip_submissions (contributor_slug,destination_slug,destination,trip_start,trip_end,day_count,total_cost_inr,total_cost_usd,cost_stay,cost_food,cost_transport,cost_activities,cost_misc,top_notes,highlight,status) VALUES ('ananya-mumbai','goa-india','Goa (North + interior)','2026-02-12','2026-02-21',9,27800,327,11400,6800,4200,3800,1600,'["Skip Calangute. Stay in Aldona or Assagao if you can afford the extra ₹500/night.", "Scooter rental from a women-run garage in Mapusa was cheaper and less hassle than the beach-shack guys.", "Curlie''s at sunset is still worth it. Get there at 5:30, leave by 9 — after that the crowd changes."]','The Project Café in Aldona on a Wednesday afternoon — empty pool, a pile of art books, three other solo women already there.','approved');
INSERT INTO trip_submissions (contributor_slug,destination_slug,destination,trip_start,trip_end,day_count,total_cost_inr,total_cost_usd,cost_stay,cost_food,cost_transport,cost_activities,cost_misc,top_notes,highlight,status) VALUES ('leila-delhi','rishikesh-india','Rishikesh — yoga + Ganga aarti','2026-03-08','2026-03-14',6,18400,217,7200,3600,3800,2800,1000,'["Tapovan side > Lakshman Jhula side for solo women. Quieter, fewer hawkers, better cafés.", "Volvo from Delhi (overnight) saved a hotel night and ₹2,500.", "Don''t pay for a Ganga aarti ''guided experience''. Just turn up at Triveni Ghat at 6pm."]','Sunrise Ganga walk from Tapovan to Lakshman Jhula — alone for 40 minutes, then 80 monkeys.','approved');
INSERT INTO trip_submissions (contributor_slug,destination_slug,destination,trip_start,trip_end,day_count,total_cost_inr,total_cost_usd,cost_stay,cost_food,cost_transport,cost_activities,cost_misc,top_notes,highlight,status) VALUES ('sara-berlin','jaipur-india','Jaipur — Pink City circuit','2026-01-22','2026-01-26',4,22300,262,9800,4200,3100,4400,800,'["Composite Ticket is the only smart move — ₹400 for 5 monuments, valid 2 days.", "Pink City Rickshaw Company (women drivers) is worth every rupee for a half-day Old City tour.", "Anokhi Café is the breakfast you want after a 6am Amber Fort trip. Not a tourist trap."]','Block-printing workshop at the Anokhi Museum. Three hours, two new friends, one ruined kurta.','approved');
INSERT INTO trip_submissions (contributor_slug,destination_slug,destination,trip_start,trip_end,day_count,total_cost_inr,total_cost_usd,cost_stay,cost_food,cost_transport,cost_activities,cost_misc,top_notes,highlight,status) VALUES ('ananya-mumbai','kasol-india','Kasol → Tosh trek','2026-04-02','2026-04-09',7,14600,172,5400,3200,4200,1200,600,'["Volvo Delhi → Bhuntar overnight, then shared cab to Kasol. ₹1,800 total, beats flying.", "Stayhappy Hostel in Kasol has the only female-only dorm I trust in the valley.", "Tosh village hike is doable solo in May. Don''t try in monsoon."]','Reading on the rocks above the Parvati at 7am with no one within shouting distance.','approved');
INSERT INTO trip_submissions (contributor_slug,destination_slug,destination,trip_start,trip_end,day_count,total_cost_inr,total_cost_usd,cost_stay,cost_food,cost_transport,cost_activities,cost_misc,top_notes,highlight,status) VALUES ('devika-pune','hampi-india','Hampi heritage walk','2026-02-26','2026-03-02',4,11200,132,3800,2600,2400,1800,600,'["Stay on the Hippie Island side (Virupapur Gaddi). Hampi Bazaar side is dry, no alcohol, by 9pm dead.", "Rent a moped from Hampi Bazaar — boulders are too far apart to walk.", "Sunrise at Matanga Hill is worth the 5am climb. Sunset at Hemakuta is the easier alternative."]','Sitting alone in the Achyutaraya temple courtyard for 90 minutes. Not a soul. Late February is the secret.','approved');
INSERT INTO trip_submissions (contributor_slug,destination_slug,destination,trip_start,trip_end,day_count,total_cost_inr,total_cost_usd,cost_stay,cost_food,cost_transport,cost_activities,cost_misc,top_notes,highlight,status) VALUES ('kavya-chennai','kochi-india','Fort Kochi + backwaters','2026-03-19','2026-03-25',6,13800,162,4800,3200,2800,2400,600,'["₹4 government ferry between Fort Kochi and Ernakulam — 25 minutes, sunset view, unbeatable.", "Skip the houseboat overnight scam. Day trip from Alleppey is enough and ₹4,000 cheaper.", "Kashi Art Café is overhyped. Kayees Biryani is not."]','A solo Kathakali show at Kerala Kathakali Centre. Front row, ₹350, makeup demo at 5pm.','approved');
INSERT INTO trip_submissions (contributor_slug,destination_slug,destination,trip_start,trip_end,day_count,total_cost_inr,total_cost_usd,cost_stay,cost_food,cost_transport,cost_activities,cost_misc,top_notes,highlight,status) VALUES ('leila-delhi','udaipur-india','Udaipur — lake circuit','2026-01-15','2026-01-19',4,19800,233,8400,3800,2600,4200,800,'["Stay in Hanuman Ghat side, not Lal Ghat. Same view, half the price, zero touts.", "Sadhna Collective HQ visit is a 30-minute auto from the city — and the heart of women-led Rajasthan.", "Avoid the big-name lake palace boat ride. The ₹400 government ferry to Jagmandir does the job."]','Sunrise from the cliff above Bagore Ki Haveli. Bring chai. No one else is up there at 6am.','approved');
INSERT INTO trip_submissions (contributor_slug,destination_slug,destination,trip_start,trip_end,day_count,total_cost_inr,total_cost_usd,cost_stay,cost_food,cost_transport,cost_activities,cost_misc,top_notes,highlight,status) VALUES ('neha-jaipur','jaipur-india','Jaipur for repeat visitors','2026-03-04','2026-03-08',4,15600,184,6800,3200,2200,2600,800,'["Skip the Pink City. Spend two days in Amer (the village, not just the fort) and Nahargarh.", "Eat at LMB only once. Then go where I go: Sahu Chai for breakfast, Rawat for kachori.", "Block printing in Bagru (45 min from Jaipur) is more rewarding than Sanganer."]','Watching Holika Dahan at Hawa Mahal Bazaar from a friend''s terrace. No tourists. Just neighbors.','approved');
INSERT INTO trip_submissions (contributor_slug,destination_slug,destination,trip_start,trip_end,day_count,total_cost_inr,total_cost_usd,cost_stay,cost_food,cost_transport,cost_activities,cost_misc,top_notes,highlight,status) VALUES ('priya-kochi','rishikesh-india','Rishikesh — yoga teacher training prep','2026-02-04','2026-02-12',8,32400,381,14600,5200,4400,7400,800,'["Anand Prakash Yoga Ashram is the only TTC I''d send a beginner to. Avoid the Tapovan strip mills.", "₹6/day Ganga ferry (not the tourist boat) is the secret crossing.", "Pre-book your YTT in October. By February the good ones are gone."]','First handstand in 11 years on a sandbank by Ram Jhula at sunrise. No witnesses.','approved');
INSERT INTO trip_submissions (contributor_slug,destination_slug,destination,trip_start,trip_end,day_count,total_cost_inr,total_cost_usd,cost_stay,cost_food,cost_transport,cost_activities,cost_misc,top_notes,highlight,status) VALUES ('ananya-mumbai','varanasi-india','Varanasi — three slow days','2026-03-25','2026-03-28',3,8900,105,2700,2400,1800,1500,500,'["Stay at Hostel LaVie''s female dorm — the only one I trust on the ghats.", "Take the female-rowed sunrise boat (collective near Assi Ghat) instead of the tourist boatmen.", "Brown Bread Bakery is base camp. Set up your day from there with chai and WiFi."]','Aarti at Assi Ghat from a rooftop with three Israeli women I''d met that morning at Brown Bread.','approved');
INSERT INTO trip_submissions (contributor_slug,destination_slug,destination,trip_start,trip_end,day_count,total_cost_inr,total_cost_usd,cost_stay,cost_food,cost_transport,cost_activities,cost_misc,top_notes,highlight,status) VALUES ('riya-bangalore','bangalore-india','A weekend in Bangalore (when you live in Bangalore)','2026-04-12','2026-04-14',2,4800,56,0,1800,800,1900,300,'["Lahe Lahe in Indiranagar on a Saturday morning = tea + a women-only writing circle.", "Champaca Books in Vasanth Nagar is the bookstore I send everyone to.", "Skip the breweries on Church Street. Try Toit only on a Tuesday."]','A four-hour solo brunch at Cinnamon, with one chai too many and zero apologies.','approved');
INSERT INTO trip_submissions (contributor_slug,destination_slug,destination,trip_start,trip_end,day_count,total_cost_inr,total_cost_usd,cost_stay,cost_food,cost_transport,cost_activities,cost_misc,top_notes,highlight,status) VALUES ('sara-berlin','delhi-india','Delhi for a returning foreigner','2026-04-18','2026-04-22',4,24600,290,11200,4400,3800,4400,800,'["Hauz Khas Village > Paharganj for a returning foreigner. Pay the extra ₹1,500/night.", "Metro is the cheat code. ₹70 for a day pass beats every Uber I''ve taken in Delhi.", "Old Delhi food walk with a women-led tour (Storytrails or similar) is worth the ₹2,500."]','An afternoon at the Sunder Nursery in February — 90 acres, almost empty, ₹35 entry.','approved');
